file = "agent.sa"
engine = "gemini"
with_default_functions = true

[[mcp_server]]
command = "common-tools"
args = []

# [[mcp_server]]
# command = "uvx"
# args = ["mcp-server-git", "--repository", "."]
